import type { Metadata, Viewport } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import {
  Fraunces,
  Karla,
  Baloo_2,
  Nunito,
  Caveat_Brush,
  Kalam,
  Fredoka,
  Caveat,
} from "next/font/google";
import "./globals.css";
import "./revamp.css";
import "./skins/palettes.css";
import "./skins/skins.css";
import "./skins/port-base.css";
// Ported skins (generated by scripts/port-skins.mjs from design/skins/*.css).
import "./skins/skin-soft.css";
import "./skins/skin-play.css";
import "./skins/skin-paper.css";
import "./skins/skin-clay.css";
import "./skins/skin-scrap.css";
import "./skins/port-overrides.css";
import "./skins/clay-real.css";
import "./skins/scrap-real.css";
import { SketchLayer } from "@/components/SketchLayer";

const cabinet = localFont({
  src: [
    { path: "../public/fonts/CabinetGrotesk-Regular.woff2", weight: "400" },
    { path: "../public/fonts/CabinetGrotesk-Bold.woff2", weight: "700" },
    { path: "../public/fonts/CabinetGrotesk-Extrabold.woff2", weight: "800" },
  ], variable: "--font-cabinet", display: "swap",
});

/* Skin families (one pair per skin, from each skin's META line in
   design/skins/skin-*.css). Loaded once here and exposed as CSS variables;
   app/skins/skins.css maps them onto --font-display/--font-body per
   html[data-skin]. Only the default skin's fonts preload — the rest load
   lazily when their skin is chosen. */
const fraunces = Fraunces({ subsets: ["latin"], axes: ["opsz"], variable: "--font-fraunces", display: "swap" });
const karla = Karla({ subsets: ["latin"], variable: "--font-karla", display: "swap" });
const baloo = Baloo_2({ subsets: ["latin"], variable: "--font-baloo", display: "swap", preload: false });
const nunito = Nunito({ subsets: ["latin"], variable: "--font-nunito", display: "swap", preload: false });
const caveatBrush = Caveat_Brush({ weight: "400", subsets: ["latin"], variable: "--font-caveat-brush", display: "swap", preload: false });
const kalam = Kalam({ weight: ["300", "400", "700"], subsets: ["latin"], variable: "--font-kalam", display: "swap", preload: false });
const fredoka = Fredoka({ subsets: ["latin"], variable: "--font-fredoka", display: "swap", preload: false });
const caveat = Caveat({ subsets: ["latin"], variable: "--font-caveat", display: "swap", preload: false });

const SKIN_FONT_CLASSNAMES = [
  fraunces.variable,
  karla.variable,
  baloo.variable,
  nunito.variable,
  caveatBrush.variable,
  kalam.variable,
  fredoka.variable,
  caveat.variable,
].join(" ");

// Explicit viewport export (Next 16 Metadata API: `viewport` object, not a
// <meta> tag or metadata.viewport) — Safari must render 1:1 with Chrome.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Draw under the notch / home indicator so env(safe-area-inset-*) engages and
  // the app renders edge-to-edge like a native shell.
  viewportFit: "cover",
  // Default look (soft + honey) light background; dark picks it up from CSS.
  themeColor: "#FCF9F1",
};

export const metadata: Metadata = {
  title: "Giggle — Good to be together",
  description: "A little place to hang out with your people. Start a squad, share an invite, and settle into a group video call.",
  manifest: "/manifest.webmanifest",
  applicationName: "Giggle",
  // Installable, fullscreen "Add to Home Screen" behaviour on iOS — makes the
  // web app launch chrome-less like a native app, with a translucent status bar
  // over the app's own header.
  appleWebApp: {
    capable: true,
    title: "Giggle",
    statusBarStyle: "black-translucent",
  },
  formatDetection: { telephone: false },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Default look attributes match DEFAULT_LOOK (soft + honey, light SSR
    // fallback for auto); theme-init.js rewrites them from localStorage
    // before first paint. suppressHydrationWarning covers the swap.
    <html
      lang="en"
      suppressHydrationWarning
      className={`${cabinet.variable} ${SKIN_FONT_CLASSNAMES}`}
      data-skin="soft"
      data-palette="honey"
      data-mode="light"
      data-theme="light"
    >
      <body suppressHydrationWarning style={{ fontFamily: "var(--font-body)" }}>
        {/* External beforeInteractive script (loaded by src, not inline
            children) applies the saved look pre-paint without the React 19
            "script tag while rendering" warning. */}
        <Script id="giggle-theme-init" src="/theme-init.js" strategy="beforeInteractive" />
        {/* Sketch (Doodle skin) renderer — runs only under data-skin="paper". */}
        <SketchLayer />
        {children}
      </body>
    </html>
  );
}
